pushpull/__init__.py
import os

from pushpull.app import app
from pushpull.main import bp as main_bp
from pushpull.filters import register_filters
from pushpull.teacher_dash import bp as teacher_dash_bp


register_filters(app)
app.register_blueprint(main_bp)
app.register_blueprint(teacher_dash_bp)


if __name__ == '__main__':
    port = int(os.getenv('PORT', 5000))
    app.run(debug=True, host='0.0.0.0', port=port)

pushpull/app.py
import os
from pathlib import Path
from typing import Any

from dotenv import load_dotenv
from flask import Flask
from flask import request
from flask import Response
from flask import abort

from pushpull import errors


app = Flask(__name__, instance_relative_config=True)

path = os.getenv('DOTENV', '.env_development')
assert path
load_dotenv(Path(path).resolve())

db_url = os.environ['DATABASE_URL']
if db_url.startswith("postgres://"):
    db_url = db_url.replace("postgres://", "postgresql://", 1)

secret = os.getenv('FLASK_SECRET_KEY', 'notasecret')

app.config.from_mapping(
    SECRET_KEY=secret,
    SQLALCHEMY_DATABASE_URI=db_url,
)

# Load config overrides
app.config.from_pyfile('config.py', silent=True)


@app.before_request
def auth() -> Any:
    required_password = os.getenv('HTTP_PASSWORD')
    if not required_password:
        return

    def fail() -> Any:
        resp = Response('Authorization required', 401)
        resp.headers['WWW-Authenticate'] = 'Basic'
        return resp

    auth = request.authorization
    if not auth or not auth.password or auth.password != required_password:
        return fail()


@app.errorhandler(errors.ErrorBase)
def handle_error(e: errors.ErrorBase):
    abort(e.status_code)

pushpull/main.py
import os

import pushpull.aeries
from pushpull.app import app
from pushpull.filters import register_filters
from pushpull.routes.main import bp as main_bp
from pushpull.routes.teacher_dash import bp as teacher_dash_bp


register_filters(app)
app.register_blueprint(main_bp)
app.register_blueprint(teacher_dash_bp)


if __name__ == '__main__':
    port = int(os.getenv('PORT', 5000))
    app.run(debug=True, host='0.0.0.0', port=port)

pushpull/routes/main.py
from flask import Blueprint, render_template

from pushpull.model import *


bp = Blueprint('main', __name__, url_prefix='/')


@bp.route('/')
def home():
    return render_template(
        'home.html',
        block=Block.upcoming()[0],
        teachers=Teacher.all_by_name(),
    )

pushpull/routes/teacher_dash.py
from flask import Blueprint
from flask import redirect
from flask import render_template
from flask import request
from flask import session as flask_session
from flask import url_for

from pushpull.model import *


bp = Blueprint('teacher_dash', __name__, url_prefix='/teacher')


@bp.route('/<int:teacher_id>/block/<int:block_id>/')
def dash(teacher_id: int, block_id: int):
    current_teacher = Teacher.get(teacher_id)
    block = Block.get(block_id)
    blocks = Block.upcoming()
    entries = (
        session.query(Student)
        .outerjoin(Request, (Request.student_id == Student.id) &
            (Request.block_id == block_id))
        .outerjoin(Assignment, (Assignment.student_id == Student.id) &
            (Assignment.period == block.period))
        .filter((Assignment.teacher_id == teacher_id) |
            (Request.destination_teacher_id == teacher_id))
        .order_by(Student.last_name)
        .add_entity(Request)
        .all()
    )
    result = render_template(
        'teacher_dash.html',
        current_teacher=current_teacher,
        block=block,
        blocks=blocks,
        entries=entries,
        alert=flask_session.get('alert'),
        status=flask_session.get('status'),
        teachers=Teacher.all_by_name(),
    )
    flask_session.clear()
    return result


@bp.route('/<int:teacher_id>/block/<int:block_id>/pull/')
def pull(teacher_id: int, block_id: int):
    current_teacher = Teacher.get(teacher_id)
    block = Block.get(block_id)
    query = (
        session.query(Student, Request)
        .outerjoin(Request, (Request.student_id == Student.id) &
            (Request.block_id == block_id))
        .outerjoin(Assignment, (Assignment.student_id == Student.id) &
            (Assignment.period == block.period))
        .filter(Assignment.teacher_id != teacher_id)
    )

    try:
        s = '%' + request.args['search'] + '%'
        query = query.filter(Student.first_name.ilike(s) |
            Student.last_name.ilike(s))
    except KeyError:
        pass

    entries = query.order_by(Student.last_name).all()
    return render_template(
        'pull.html',
        current_teacher=current_teacher,
        block=block,
        entries=entries,
    )


@bp.route('/<int:teacher_id>/block/<int:block_id>/action/', methods=['POST'])
def action(teacher_id: int, block_id: int):
    status = 'success'
    alert = None
    if 'approve' in request.form:
        student_id = int(request.form['approve'])
        Request.approve(block_id, student_id)
        alert = f'Approved request (SID {student_id})'
    elif 'delete' in request.form:
        student_id = int(request.form['delete'])
        Request.delete(block_id, student_id)
        alert = f'Denied request (SID {student_id})'
    elif 'pull' in request.form:
        student_id = int(request.form['pull'])
        Student.pull(student_id, teacher_id, block_id)
        alert = f'Pull requested (SID {student_id})'
    elif 'push' in request.form:
        if not request.form['teacher']:
            status = 'info'
            alert = 'You must select a teacher to push to.'
        else:
            student_id = int(request.form['push'])
            dst_teacher_id = int(request.form['teacher'])
            Student.push(student_id, dst_teacher_id, block_id)
            alert = f'Push requested (SID {student_id})'
    flask_session['status'] = status
    if alert:
        flask_session['alert'] = alert
    url = url_for('.dash', teacher_id=teacher_id, block_id=block_id)
    return redirect(url, code=303)

pushpull/templates/base.html
<!DOCTYPE html>

{% set app_title = 'Push<->Pull' %}

<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %} - {{app_title}}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
    <style type="text/css">
        .table td {
            vertical-align: middle;
        }
        .table th {
            vertical-align: middle;
        }
    </style>
    {% block head %}{% endblock %}
  </head>

  <body>
  <nav class="navbar is-primary" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <a href="{{url_for('main.home')}}" class="navbar-item"><span class="is-size-4"><b>{{app_title}}</b></span></a>
    </div>
  </nav>

  {% block body %}{% endblock %}
  </body>
</html>

pushpull/templates/home.html
<!DOCTYPE html>

{% set app_title = 'Push<->Pull' %}

<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{app_title}}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
    <style type="text/css">
        .table td {
            vertical-align: middle;
        }
        .table th {
            vertical-align: middle;
        }
    </style>
  </head>
  <body>
    <section class="hero is-primary is-fullheight">
      <div class="hero-body">
        <div class="container has-text-centered">
          <p class="title">
            {{app_title}}
          </p>
          <div class="field">
            <div class="control">
              <div class="select">
                <select onchange="location = this.value;">
                  <option></option>
                  {% for teacher in teachers %}
                    <option value="{{url_for('teacher_dash.dash', teacher_id=teacher.id, block_id=block.id)}}">{{teacher.name}}</option>
                  {% endfor %}
                </select>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </body>
</html>

pushpull/templates/pull.html
{% extends 'base.html' %}

{% block title %}
  Pull student - {{current_teacher.name}} - {{format_block_time(block)}}
{% endblock %}

{% macro format_block_time(block) %}
  {{block.day.strftime('%A, %d %B')}} {{block.period}}
{% endmacro %}

{% macro teacher_view(view) %}
  {{url_for(view, teacher_id=current_teacher.id, block_id=block.id)}}
{% endmacro %}

{% block body %}
  <section class="section">
    <div class="container">
      <h1 class="title is-3">Pull student</h1>
      <form>
        <div class="field has-addons">
          <div class="control">
            <input class="input" name="search" type="text" placeholder="Search students">
          </div>
          <div class="control">
            <button type="submit" class="button is-info">
              <span class="icon"><i class="fas fa-search"></i></span>
            </button>
          </div>
        </div>
      </form>
      <table class="table is-striped">
        <thead>
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Existing request</th>
          </tr>
        </thead>
        <tbody>
          {% for student, request in entries %}
            <tr>
              <td>{{student.id}}</td>
              <td>{{student.name}}</td>
              <td>
                {% if request %}
                  {# TODO: Make this a template of some sort #}
                  <div class="field has-addons">
                    {% if request.destination_teacher == current_teacher %}
                      <div class="control">
                        <a class="button is-small is-info">From</a>
                      </div>
                      <div class="control">
                        <a class="button is-small"><b>{{request.assigned_teacher.name if request.assigned_teacher else 'n/a'}}</b></a>
                      </div>
                    {% else %}
                      <div class="control">
                        <a class="button is-small is-danger">To</a>
                      </div>
                      <div class="control">
                        <a class="button is-small"><b>{{request.destination_teacher.name}}</b></a>
                      </div>
                    {% endif %}
                  </div>
                {% else %}
                  <form action="{{teacher_view('.action')}}" method="post">
                    <div class="field has-addons">
                      <div class="control">
                        <button
                          type="submit"
                          name="pull"
                          value="{{student.id}}"
                          class="button is-info is-outlined"
                        >
                          Pull
                        </button>
                      </div>
                    </div>
                  </form>
                {% endif %}
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </section>
{% endblock %}

pushpull/templates/redirect.html
<!DOCTYPE html>

{% set app_title = 'Push<->Pull' %}

<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{app_title}}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
    <style type="text/css">
        .table td {
            vertical-align: middle;
        }
        .table th {
            vertical-align: middle;
        }
        .subtitle {
          font-weight: bold;
        }
        .link {
          text-decoration: underline;
        }
        .link:hover {
          color: rgb(229, 229, 229) !important;
        }
    </style>
  </head>
  <body>
    <section class="hero is-primary is-fullheight">
      <div class="hero-body">
        <div class="container has-text-centered">
          <p class="title">
            Update your bookmarks
          </p>
          <p class="subtitle">
            Push&lt;-&gt;Pull has moved to
            <a
              class="link"
              href="https://pushpull.mmcallister.me"
            >
              https://pushpull.mmcallister.me
            </a>
          </p>
        </div>
      </div>
    </section>
  </body>
</html>

pushpull/templates/teacher_dash.html
{% extends 'base.html' %}

{% block title %}
  {{current_teacher.name}} - {{format_block_time(block)}}
{% endblock %}

{% block head %}
  <meta http-equiv="refresh" content="30">
{% endblock %}

{# Strikes out text if the student is leaving this classroom #}
{% macro strike_outgoing(text, student, request) %}
  {% if request and request.destination_teacher != current_teacher %}
    <s>{{text}}</s>
  {% else %}
    {{text}}
  {% endif %}
{% endmacro %}

{% macro format_block_time(block) %}
  {{block.day.strftime('%A, %d %B')}} {{block.period}}
{% endmacro %}

{% macro teacher_view(view) %}
  {{url_for(view, teacher_id=current_teacher.id, block_id=block.id)}}
{% endmacro %}

{% block body %}
  <section class="section">
    <div class="container">
      {% if alert %}
        <div class="notification is-{{status}} is-light"><p>{{alert}}</p></div>
      {% endif %}
      <h1 class="title is-3">{{current_teacher.name}}'s homeroom</h1>
      <div class="tabs">
        <ul>
          {% for b in blocks %}
            <li {% if b == block %}class="is-active"{% endif %}>
              <a href="{{url_for('.dash', teacher_id=current_teacher.id, block_id=b.id)}}">
                {{format_block_time(b)}}
              </a>
            </li>
          {% endfor %}
        </ul>
      </div>
      <table class="table is-striped">
        <thead>
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Transfer</th>
          </tr>
        </thead>
        <tbody>
          {% for student, request in entries %}
            <tr>
              <th>{{strike_outgoing(student.id, student, request)}}</th>
              <td>
                {% if request %}
                  <b>{{strike_outgoing(student.name, student, request)}}</b>
                {% else %}
                  {{student.name}}
                {% endif %}
              </td>
              <td>
                <form action="{{teacher_view('.action')}}" method="post">
                  {% if request %}
                    <div class="field has-addons">
                      {% if request.destination_teacher == current_teacher %}
                        <div class="control">
                          <a class="button is-small is-info">From</a>
                        </div>
                        <div class="control">
                          <a class="button is-small"><b>{{request.assigned_teacher.name if request.assigned_teacher else 'n/a'}}</b></a>
                        </div>
                      {% else %}
                        <div class="control">
                          <a class="button is-small is-danger">To</a>
                        </div>
                        <div class="control">
                          <a class="button is-small"><b>{{request.destination_teacher.name}}</b></a>
                        </div>
                      {% endif %}
                      {% if request.requester == current_teacher %}
                        {% if request.approved %}
                          <div class="control">
                            <a class="button is-small is-success is-light"><span>Approved</span></a>
                          </div>
                        {% else %}
                          <div class="control">
                            <a class="button is-small is-warning is-light">Pending approval</a>
                          </div>
                        {% endif %}
                      {% elif request.requester %}
                        {% if request.approved %}
                          <div class="control">
                            <a class="button is-small is-success is-light"><span>Approved by <b>me</b></span></a>
                          </div>
                        {% else %}
                          <div class="control">
                            <a class="button is-small is-info is-light">Needs approval</a>
                          </div>
                          <div class="control">
                            <button
                              type="submit"
                              name="approve"
                              value="{{student.id}}"
                              class="button is-small is-success is-outlined"
                            >
                              <span class="icon"><i class="fas fa-check"></i></span>
                            </button>
                          </div>
                        {% endif %}
                      {% endif %}
                      {% if not request.requester %}
                        <div class="control">
                          <a class="button is-small is-light">Automatic</a>
                        </div>
                      {% else %}
                        <div class="control">
                          <button
                            type="submit"
                            name="delete"
                            value="{{student.id}}"
                            class="button is-small has-text-grey is-outlined"
                          >
                            <span class="icon"><i class="fas fa-times"></i></span>
                          </button>
                        </div>
                      {% endif %}
                    </div>
                  {% else %}
                    <div class="field has-addons">
                      <div class="control">
                        <div class="select is-small">
                          <select name="teacher">
                            <option></option>
                            {% for teacher in teachers %}
                              <option value="{{teacher.id}}">{{teacher.name}}</option>
                            {% endfor %}
                          </select>
                        </div>
                      </div>
                      <div class="control">
                        <button
                          type="submit"
                          name="push"
                          value="{{student.id}}"
                          class="button is-small is-outlined"
                        >
                          Request push
                        </button>
                      </div>
                    </div>
                  {% endif %}
                </form>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
      <a href="{{teacher_view('.pull')}}" class="button is-info">
        <span class="icon"><i class="fas fa-plus"></i></span>
        <span>Request a student from another homeroom</span>
      </a>
    </div>
  </section>
{% endblock %}